language: android
android:
  components:
    - tools
    - platform-tools
    # The SDK version used to compile your project
    - android-27
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
  before_install:
    - yes | sdkmanager "platforms;android-27"
  script:
    - chmod +x ./gradlew build connectedCheck