language: android
android:
  components:
    - tools
    - build-tools-27.0.3
    - platform-tools
    - android-27
    - extra-android-m2repository
  before_install:
    - yes | sdkmanager "platforms;android-27"
  script:
    - chmod +x ./gradlew build connectedCheck